config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :rooms
  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  def timestamp
  created_at.strftime('%H:%M:%S %d %B %Y')
  end
  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  def id_to_select
  title
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  def name
  email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include LoadAndAuthorizeResource
  protect_from_forgery with: :exception
end

app/controllers/line_controller.rb
class LineController < ApplicationController
  def index
  end
  def show
    ActionCable.server.broadcast 'lines',
      fromx: params[:fromx],
      fromy: params[:fromy],
      tox: params[:tox],
      toy: params[:toy],
      color: params[:color]
    head :ok
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    # @room = Room.find(params[:id])

    @room = Room.includes(:messages).find_by(id: params[:id])
    k = @room.id_to_select
    @picture_id = k
    @message = Message.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    @room.save
    redirect_to @room
  end


  def update
    @room = Room.find(params[:id])

    if @room.update(room_params)
      redirect_to @room
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    redirect_to rooms_path
  end

  private
  def room_params
    params.require(:room).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  load_and_authorize_resource
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
  opts[:alt] = user.name
  image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
            opts
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/Shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wrs</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <% unless @picture_id.nil? %>
    <script>
    window.image_id = "<%= escape_javascript( @picture_id ) %>";

    window.connected = function () {
      App.draw.watch("<%= escape_javascript( @picture_id ) %>");
    }
    </script>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://bootswatch.com/flatly/bootstrap.min.css" media="screen">
    <link rel="stylesheet" href="https://bootswatch.com/assets/css/custom.min.css">
    <% unless flash.empty? %>
<script type="text/javascript">
    <% flash.each do |f| %>
  <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
   toastr['<%= type %>']('<%= f[1] %>');
     <% end %>
     </script>
<% end %>
<style>
#messages {
  max-height: 450px;
  overflow-y: auto;
  .avatar {
    margin: 0.5rem;
  }
}
</style>
  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <a href="/" class="navbar-brand">WRS</a>
              <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
              <ul class="nav navbar-nav">
                <li>
                  <a href="/" class="" >Home</a>
                </li>
                <li>
                  <a href="/rooms" class="">Rooms</a>
                </li>
                  </ul>
               <ul class="nav navbar-nav navbar-right">
                 <% if user_signed_in? %>
                 <li><a class=""><%= current_user.name %></a></li>
                 <li><%= link_to 'Edit profile', edit_user_registration_path,  class: "" %></li>
                 <li><%= link_to 'Log out', destroy_user_session_path, class: "",  :method => :delete %></li>
               <% else %>
                 <li><%= link_to 'Log in', new_user_session_path, class: "" %></li>
                 <li><%= link_to 'Sign up', new_user_registration_path, class: "" %></li>
                 <% end %>
              </ul>
            </div>
          </div>
        </div>
        <% if !user_signed_in? %>
        <div class="container">
        </br>
        </br>
        </br>
        <div class="progress" style="margin-left:5%;">
        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
        aria-valuemin="0" aria-valuemax="100" style="width:100%">
        <a href="users/sign_in" class="" >Zarejestruj się</a>, aby korzystać z wszystkich możliwości aplikacji!
        </div>
        </div>
        <% end %>
        <div class="container">
          <% if user_signed_in? %>
        </br>
        </br>
        </br>
        <% end %>
          <%= yield %>
          <div class="container">
   <footer>
       <div class="row">
         <div class="col-lg-12">

           <p>Projekt Zespołowy - 2017</a>.
           <p>Based on <a href="http://getbootstrap.com" rel="nofollow">Bootstrap</a>. Icons from <a href="http://fortawesome.github.io/Font-Awesome/" rel="nofollow">Font Awesome</a>. Web fonts from <a href="http://www.google.com/webfonts" rel="nofollow">Google</a>.</p>

         </div>
       </div>

     </footer>
</div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="container">
  <h2>Edit room</h2>
<%= form_for @room do |f| %>



<div class="form-group">
  <%= f.label :title, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :title, class: "form-control opacity" %>
    </br>
  </div>
</div>

<div class="form-group">
  <%= f.label :text, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :text, class: "form-control opacity" %>
    </br>
  </div>
</div>

<div class="form-group">
			<div class="text-center">

  <div class="form-group">
      <button type="submit" class="btn btn-success btn-circle btn-outline glyphicon glyphicon-ok"></button>
      <%= link_to "", rooms_path, class: "btn btn-default btn-circle btn-outline glyphicon glyphicon-arrow-left" %>
</div>
  </div>
  </div>
</div>
<% end %>

app/views/rooms/index.html.erb
    <div class="container">
                <h2>Rooms</h2>
                <div class="table-responsive">
                <table class="table table-bordered table-striped table-background opacity">
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th class="text-center"></th>
                  </tr>

                  <% @rooms.each do |room| %>
                    <tr>
                      <td class="text-left"><%= room.title %></td>
                      <td class="text-left"><%= room.text %></td>
                      <td class="text-center"> <%= link_to "", room_path(room), class: "btn btn-default btn-circle btn-outline glyphicon glyphicon-search" %>
                      <% if user_signed_in? %>
                          <% if current_user == room.user %>
                      <%= link_to "", room_path(room) , method: :delete, class: "btn btn-default btn-circle btn-outline glyphicon glyphicon-remove" %></td>
                      <% end %>
                      <% end %>
                    </tr>
                  <% end %>
                </table>
                </div>
                <% if user_signed_in? %>
                <%= link_to "", new_room_url, class: "btn btn-default btn-circle btn-outline glyphicon glyphicon-plus" %></br>
                <% end %>
              </br>
      </div>

app/views/rooms/new.html.erb
<div class="container">
  <h2>Add new room</h2>
<%= form_for :room, url: rooms_path do |f| %>



<div class="form-group">
  <%= f.label :title, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :title, class: "form-control opacity" %>
    </br>
  </div>
</div>

<div class="form-group">
  <%= f.label :text, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :text, class: "form-control opacity" %>
    </br>
  </div>
</div>

<div class="form-group">
			<div class="text-center">

  <div class="form-group">
      <button type="submit" class="btn btn-success btn-circle btn-outline glyphicon glyphicon-plus"></button>
      <%= link_to "", rooms_path, class: "btn btn-default btn-circle btn-outline glyphicon glyphicon-arrow-left" %>
</div>
  </div>
  </div>
</div>
<% end %>

app/views/rooms/show.html.erb
<div class="container">
  <h2>Show room</h2>
  <% provide :title, "Draw | Room: " + @picture_id %>
  <p>
  <b>Room: <%= @picture_id %></b><br/>
  Draw below for all to see.
  </p>
  <canvas id="easel" width="640" height="480">Your browser does not support canvas</canvas>

  <br/>
<% if user_signed_in? %>
  <button onclick="App.draw.clear('<%= escape_javascript( @picture_id ) %>')">Clear</button>
  <% end %>
</br>
</br>
   <div id="messages" data-room-id="<%= @room.id %>">
     <%= render @room.messages %>
   </div>

<% if user_signed_in? %>
    <%= form_for @message, url: '#' do |f| %>
     <%= hidden_field_tag 'room_id', @room.id %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>
<% end %>
</br>
   <div class="form-group">
       <%= link_to "", rooms_path, class: "btn btn-default btn-circle btn-outline glyphicon glyphicon-arrow-left" %>
   </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron opacity">
    <h2 class="text-center">Web RPG Sessionss</h2>
<img src="https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/die-256.png" class="img-responsive center-block" alt="Smiley face" height="256" width="256">
  </div>
</div>